/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e1e3e4",
        "outline-variant": "#c7c4d7",
        "tertiary-container": "#8f3400",
        "background": "#f8f9fa",
        "on-primary-fixed-variant": "#372abf",
        "inverse-primary": "#c3c0ff",
        "on-primary-container": "#c1beff",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3132",
        "secondary-fixed": "#6ffbbe",
        "surface-container-high": "#e7e8e9",
        "on-surface": "#191c1d",
        "surface": "#f8f9fa",
        "on-secondary-container": "#00714d",
        "tertiary-fixed-dim": "#ffb597",
        "secondary-fixed-dim": "#4edea3",
        "surface-dim": "#d9dadb",
        "on-primary-fixed": "#100069",
        "error-container": "#ffdad6",
        "secondary": "#006c49",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed": "#ffdbcd",
        "inverse-on-surface": "#f0f1f2",
        "primary-container": "#4338ca",
        "outline": "#777586",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#005236",
        "primary-fixed": "#e3dfff",
        "on-tertiary-container": "#ffb393",
        "surface-container": "#edeeef",
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "primary": "#2a14b4",
        "secondary-container": "#6cf8bb",
        "on-secondary-fixed": "#002113",
        "on-tertiary-fixed": "#360f00",
        "on-background": "#191c1d",
        "on-surface-variant": "#464554",
        "tertiary": "#692400",
        "on-primary": "#ffffff",
        "surface-tint": "#5148d7",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "48px",
        "md": "24px",
        "base": "8px",
        "sm": "12px",
        "xs": "4px",
        "xl": "64px",
        "gutter": "16px",
        "margin-mobile": "20px",
        "lg": "40px"
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
